<script setup lang="ts">
import type { Report, SimilarItem } from '@/lib/muzakData';
import MoodBar from './MoodBar.vue';
import Sleeve from './Sleeve.vue';

const props = defineProps<{
    report: Report;
    moodVariant: 'linear' | 'dots' | 'two-tone';
    heroLayout: 'side-by-side' | 'stacked' | 'full-bleed';
}>();

const emit = defineEmits<{
    openSimilar: [item: SimilarItem];
}>();

const releaseDate = new Date(props.report.year, 4, 8).toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
});

const generatedDate = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
</script>

<template>
    <article class="mz-report" :class="`mz-report--${heroLayout}`">
        <header class="mz-hero" :class="`mz-hero--${heroLayout}`">
            <!-- Cover: shown before meta for side-by-side/full-bleed, after for stacked -->
            <div
                v-if="heroLayout !== 'stacked'"
                class="mz-hero-cover"
                :class="`mz-hero-cover--${heroLayout}`"
            >
                <Sleeve :cover-id="report.coverId" />
            </div>

            <div class="mz-hero-meta">
                <div class="mz-hero-eyebrow">
                    <span>Analysis · {{ report.spotifyUrl }}</span>
                </div>
                <h1 class="mz-hero-title">{{ report.title }}</h1>
                <div class="mz-hero-artist">
                    <span>{{ report.artist }}</span>
                    <span class="mz-dot" />
                    <span>{{ report.year }}</span>
                    <span class="mz-dot" />
                    <span>{{ report.label }}</span>
                </div>
                <div class="mz-hero-tags">
                    <span v-for="g in report.genres" :key="g" class="mz-tag">{{ g }}</span>
                </div>
                <div class="mz-hero-stats">
                    <div>
                        <span class="mz-stat-k">Tracks</span>
                        <span class="mz-stat-v">{{ report.tracks }}</span>
                    </div>
                    <div>
                        <span class="mz-stat-k">Length</span>
                        <span class="mz-stat-v">{{ report.length }}</span>
                    </div>
                    <div>
                        <span class="mz-stat-k">Released</span>
                        <span class="mz-stat-v">{{ releaseDate }}</span>
                    </div>
                </div>
            </div>

            <!-- Cover: shown after meta for stacked layout -->
            <div v-if="heroLayout === 'stacked'" class="mz-hero-cover mz-hero-cover--stacked">
                <Sleeve :cover-id="report.coverId" />
            </div>
        </header>

        <section class="mz-mood-section">
            <div class="mz-mood-kicker">Emotional profile</div>
            <MoodBar :mood="report.mood" :variant="moodVariant" />
        </section>

        <section v-for="(sec, i) in report.sections" :key="i" class="mz-report-section">
            <h2 class="mz-report-h">{{ sec.heading }}</h2>
            <p v-for="(p, j) in sec.paragraphs" :key="j" class="mz-report-p">{{ p }}</p>
        </section>

        <section class="mz-report-section mz-similar-section">
            <h2 class="mz-report-h">You Might Also Like</h2>
            <div class="mz-similar-row">
                <button
                    v-for="s in report.similar"
                    :key="s.title"
                    class="mz-similar-card"
                    @click="emit('openSimilar', s)"
                >
                    <div class="mz-similar-art">
                        <Sleeve :cover-id="s.coverId" />
                    </div>
                    <div class="mz-similar-title">{{ s.title }}</div>
                    <div class="mz-similar-artist">{{ s.artist }}</div>
                    <div class="mz-similar-reason">{{ s.reason }}</div>
                </button>
            </div>
        </section>

        <footer class="mz-report-footer">
            <span>Generated by Muzak · haiku-4-5 · {{ generatedDate }}</span>
        </footer>
    </article>
</template>
